# Generated by Django 5.1.6 on 2025-02-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('mpesa_code', models.CharField(max_length=20, unique=True)),
                ('paying_number', models.CharField(max_length=10)),
                ('receiving_number', models.CharField(max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
